config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
 
  resources :pub_quests
   resources :choice
   resources :votes, only: [:create]

    get '/votes/count/:id' =>'votes#count'

    get 'user_profile' => 'pub_quests#user_profile'
   
   root 'pub_quests#index'
  
   

end

app/models/choice.rb
class Choice < ActiveRecord::Base
	 belongs_to :pub_quest
	 has_many :votes, dependent: :destroy

	 has_many :users, through: :votes
end

app/models/pub_quest.rb
class PubQuest < ActiveRecord::Base
	  
    has_many :choices , :dependent => :destroy
    accepts_nested_attributes_for :choices, :reject_if => :all_blank, :allow_destroy => true
    belongs_to :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    
    
 has_many :pub_quest
 
 has_many :votes, dependent: :destroy
 has_many :choices, through: :votes
def voted_for?(pub_quest)
    choices(true).any? {
    	|v|
     v.pub_quest == pub_quest 
 }

 
end
 
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :choice
  belongs_to :pub_quest
  
  validates_uniqueness_of :pub_quest, scope: :user_id
  


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/pub_quests_controller.rb
class PubQuestsController < ApplicationController
  
  before_action :set_pub_quest, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! ,except: [:index]

  # GET /pub_quests
  # GET /pub_quests.json
  def index
    @pub_quests = PubQuest.all
  end

  # GET /pub_quests/1
  # GET /pub_quests/1.json
  def show
    @pub_quest= PubQuest.includes(:choices).find(params[:id])
    if current_user.voted_for?(@pub_quest)
      redirect_to "/votes/count/#{@pub_quest.id}"
    else
      render :show, status: :created, location: @pub_quest
    end
  end

  # GET /pub_quests/new
  def new
    @pub_quest = PubQuest.new
    2.times { choice = @pub_quest.choices.build}
  end

  # GET /pub_quests/1/edit
  def edit
  end
  
  # POST /pub_quests
  # POST /pub_quests.jsdef create
  def create
  @pub_quest = PubQuest.new(pub_quest_params)
  
    respond_to do |format|
      if @pub_quest.save
        format.html { redirect_to @pub_quest, notice: 'Pub quest was successfully created.' }
        format.json { render :show, status: :created, location: @pub_quest }
      else
        format.html { render :new }
        format.json { render json: @pub_quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pub_quests/1
  # PATCH/PUT /pub_quests/1.json
  def update
    respond_to do |format|
      if @pub_quest.update(pub_quest_params)
        format.html { redirect_to @pub_quest, notice: 'Pub quest was successfully updated.' }
        format.json { render :show, status: :ok, location: @pub_quest }
      else
        format.html { render :edit }
        format.json { render json: @pub_quest.errors, status: :unprocessable_entity }
      end
    end
  end

  def user_profile
  @mypolls = PubQuest.where(:user_id => current_user.id)
  
  end 

  # DELETE /pub_quests/1
  # DELETE /pub_quests/1.json
  def destroy
    @pub_quest.destroy
    respond_to do |format|
      format.html { redirect_to pub_quests_url, notice: 'Pub quest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pub_quest
     @pub_quest = PubQuest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pub_quest_params
    params.require(:pub_quest).permit(:name,choices_attributes: [:id,:pub_quest_id,:name,:_destroy])
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  helper :all
  def create
    if current_user && params[:pub_quest] && params[:pub_quest][:id] && params[:choice] && params[:choice][:id]
      @pub_quest = PubQuest.find_by_id(params[:pub_quest][:id])
      @choice= @pub_quest.choices.find_by_id(params[:choice][:id])
      
      if @choice && @pub_quest && !current_user.voted_for?(@pub_quest)
       @choice.votes.create(:user_id =>current_user.id, :pub_quest_id =>@pub_quest.id )
         # render js: 'alert(\'Your vote saved.\');'
          #byebug
        else
        #render js: 'alert(\'Your vote cannot be saved. Have you already voted?\');'
      end
    else
      #render js: 'alert(\'Your vote cannot be saved.\');'
    end
    redirect_to "/votes/count/#{@pub_quest.id}"
    

  end

  def count
    # puts "SUCCESS"
  # end
    @pub_quest = PubQuest.find_by_id(params[:id])
    puts @pub_quest
    @vote_count = []
    @all_choices = @pub_quest.choices
    @all_choices.each do |choice|
      c= Vote.where(pub_quest_id: @pub_quest.id , choice_id: choice.id).count
      @vote_count.push(c)
    end      
  end
  # helper_method :count

end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
     end
  
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, ("add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")"))
  end
end

app/helpers/link_to_function_helper.rb
  module LinkToFunctionHelper
  def link_to_function(name, *args, &block)
     html_options = args.extract_options!.symbolize_keys

     function = block_given? ? update_page(&block) : args[0] || ''
     onclick = "#{"#{html_options[:onclick]}; " if html_options[:onclick]}#{function}; return false;"
     href = html_options[:href] || '#'

     content_tag(:a, name, html_options.merge(:href => href, :onclick => onclick))
  end
end

app/helpers/pub_quests_helper.rb
module PubQuestsHelper

 

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinalPolling</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag   :defaults, :cache => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  
  <%= csrf_meta_tags %>

</head>
<body>
<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>
      

<%= yield %>

</body>
</html>

app/views/pub_quests/_choice_fields.html.erb
<div class="fields">
  <p>
    <%= f.label :name, "Choice" %>
    <%= link_to_remove_fields "remove", f %><br />
    <%= f.text_area :name, :rows => 3 %>
 <%= link_to_remove_fields "remove", f %><br />
  </p>

  
</div>

app/views/pub_quests/_form.html.erb
<%= form_for(@pub_quest) do |f| %>
  <% if @pub_quest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pub_quest.errors.count, "error") %> prohibited this pub_quest from being saved:</h2>

      <ul>
      <% @pub_quest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  

  <%= f.fields_for :choices do |builder| %>
  <%= render "choice_fields", :f => builder %>
  <% end %>
   <p><%= link_to_add_fields "Add Option", f, :choices %></p>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pub_quests/edit.html.erb
<h1>Editing Pub Quest</h1>

<%= render 'form' %>

<%= link_to 'Show', @pub_quest %> |
<%= link_to 'Back', pub_quests_path %>

app/views/pub_quests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pub Quests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Option</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pub_quests.each do |pub_quest| %>
      <tr>
        <td><%= pub_quest.name %></td>
      
        <td><%= link_to 'Show', pub_quest %></td>
        <td><%= link_to 'Edit', edit_pub_quest_path(pub_quest) %></td>
        <td><%= link_to 'Destroy', pub_quest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pub quest', new_pub_quest_path %>

app/views/pub_quests/new.html.erb
<h1>New Pub Quest</h1>

<%= render 'form' %>

<%= link_to 'Back', pub_quests_path %>

app/views/pub_quests/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @pub_quest.name %>
</p>
<%= form_tag votes_path, method: :post, remote: true, id: 'voting_form' do %>
<%= hidden_field_tag 'pub_quest[id]', @pub_quest.id %>
<ol>
     <% @pub_quest.choices.each do |choice| %>
    <li>  <%= radio_button_tag 'choice[id]', choice.id %>  <%= choice.name %> </li>
     <% end %>
</ol>
<% if current_user.voted_for?(@pub_quest) %>

<p>You have already voted!</p>

<% else %>
<%= submit_tag 'Vote' %>
<% end%>
<%end%>
<%= link_to 'Edit', edit_pub_quest_path(@pub_quest) %> 
<%= link_to 'Back', pub_quests_path %>

app/views/pub_quests/user_profile.html.erb
<ul>
<%= @mypolls.each do |pub_quest|%>
      <li> <%pub_quest.name%> </li>
<% end %>

</ul>

app/views/votes/count.html.erb
<%puts "In graph view"%>
<html>
<head>
  <!--Load the AJAX API-->
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  <script type="text/javascript">

      // Load the Visualization API and the corechart package.
      google.charts.load('current', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {
      // Create the data table.
      var data = new google.visualization.DataTable();
      // Declare columns
      data.addColumn('string', 'OPTION ID');
      data.addColumn('number', 'Votes');


      var vote_count = <%= escape_javascript @vote_count.to_json %>

      for(i = 0;i<vote_count.length;i++) {
        var num=i+1;
        var n = num.toString();
        data.addRow([n ,vote_count[i]]);
      }
      // Set chart options
      var options = { 'width' :400,
      'height':300};
      // Instantiate and draw our chart, passing in some options.
      var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
      chart.draw(data, options);
    }
  </script>
</head>

<body>
  <!--Div that will hold the pie chart-->
  <div id="chart_div" style="width:400; height:300"></div>

</body>
</html>